version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  discord_bot:
    container_name: bot_container
    env_file: .env
    build: .
    environment:
      TOKEN: ${TOKEN}
      LIST_ENDPOINTS: ${LIST_ENDPOINTS}
    depends_on:
      - mongo_db
    ports:
      - 8787:8787

volumes:
  mongo_db: {}
